### ISSUE TITLE
Resultクラスについての質問

### ISSUE THREAD

**Issue by THEToilet** [Den-3/ChatServer#2]
# 質問内容
@10fu3 
https://github.com/Den-3/ChatServer/blob/784a8064efe34ac57ebeef5e9a2707de43a79e55/src/main/java/jp/toufu3/ChatServer/Result.java#L24-L30

このメソッドはConsumer型を引き渡して　それに登録された無名関数？を実行してるのではないのかと思ったんですが
どういったタイミングで使うものですか？よろしくお願いします。

**Comment by 10fu3** [comment]
ビジネスロジックを実装する際に使用する予定でした。(DBへのアクセスやネットワークに接続した後の結果を取得する際に使用する予定だった)
今後このクラスは使わないと思います

**Comment by THEToilet** [comment]
ありがとうございます！
